# Blog info
blog_name: 如是我闻
slogan: 万物皆虚 万事皆允
url: http://www.pkaq.org

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: PKAQ,Gradle,Java,Spring boot,React native

home_nav:
  - name: 博客
    url: /archives
    target_blank: false #不在新页面打开
  - name: Gradle中文网
    url: http://gradlecn.org
    target_blank: true #在新页面打开
  - name: Projects
    url: /project
    target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/pkaq
    target_blank: true
  - name: 关于作者
    url: /about
    target_blank: true
# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 　

search_slogan:
  isShow: true # true|fase
  text: Show me the money ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 PKAQ@MSN.COM


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 您得支持,是我前进的动力.
  items:
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /css/qr-donate.jpg


post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/fexo-theme.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: dark # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: cd1f06c6f057506d537ab11e9f1693be

# Comment service
# disqus_shortname: pkaq
duoshuo_shortname: pkaq

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "咖啡、代码、打字母."
    - "非著名野生程序猿."
    - "会一点前,懂一些后端,在进击全栈的路上匍匐前进."
    - "P的了图片,下的了厨房,弹得了尤克里里,打的过流氓."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@pkaq"
    text_value_url: https://github.com/pkaq
  - type: mail
    icon: icon-mail
    text_key: Mail
    text_value: "pkaq@msn.com"
  - type: desc
    icon: icon-tag
    text_key: desc
    text_value:
    - "Nothing but blue skies for miles."
link:
  - name: 梁工春日的忧郁
    info: 孤星独吟
    url: http://ginryan.github.io/
    avatar: http://ginryan.github.io/img/logo.jpg

project:
  - type: personal
    name: Gradle中文文档
    url: https://github.com/pkaq/gradledoc
    intro: Gralde用户手册翻译计划
  - type: personal
    name: 跟我学Gradle
    url: http://www.jianshu.com/collection/9e24d4c23a84
    intro: Gradle中文从入门到甩锅
  - type: personal
    name: GradleSide
    url: https://github.com/pkaq/gradleside
    intro: Gradle示例大全